// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaZ67ubpm_WDjCWHupMvQgn6XmnzMUhiw',
    appId: '1:449093510661:web:f300a9e143dc9089d59e6c',
    messagingSenderId: '449093510661',
    projectId: 'kandartology',
    authDomain: 'kandartology.firebaseapp.com',
    storageBucket: 'kandartology.firebasestorage.app',
    measurementId: 'G-7V26Q7SWMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2F3iz5d1tRJn9uFdfGI7mTy083nj8MfQ',
    appId: '1:449093510661:android:d47b5add432e1dedd59e6c',
    messagingSenderId: '449093510661',
    projectId: 'kandartology',
    storageBucket: 'kandartology.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWI6JZ3Eg1_0M92lqI66ZWaxztDZkMnec',
    appId: '1:449093510661:ios:8d81a7c7cf05f342d59e6c',
    messagingSenderId: '449093510661',
    projectId: 'kandartology',
    storageBucket: 'kandartology.firebasestorage.app',
    iosBundleId: 'com.example.kandartology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWI6JZ3Eg1_0M92lqI66ZWaxztDZkMnec',
    appId: '1:449093510661:ios:8d81a7c7cf05f342d59e6c',
    messagingSenderId: '449093510661',
    projectId: 'kandartology',
    storageBucket: 'kandartology.firebasestorage.app',
    iosBundleId: 'com.example.kandartology',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaZ67ubpm_WDjCWHupMvQgn6XmnzMUhiw',
    appId: '1:449093510661:web:780f80a6be08d360d59e6c',
    messagingSenderId: '449093510661',
    projectId: 'kandartology',
    authDomain: 'kandartology.firebaseapp.com',
    storageBucket: 'kandartology.firebasestorage.app',
    measurementId: 'G-YB793KLJFG',
  );
}
